# -*- coding: utf-8 -*-
"""IQR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xikKp80cVbqgtULx8REJQD7EwkmVIFD-

How to find outliers
"""



# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline

# Define our dataset

dataset=[10,22,30,19,2,4,5,6,8,99,78,100,109,22,33,11,15,1,5,15,45,10000,76,34]

plt.hist(dataset)

outliers=[]

def detect_outliers(data):
  threshold=3  # 3rd std deviation

  mean=np.mean(data)
  std=np.std(data)

  for i in data:
    z_score=(i-mean)/std
    if np.abs(z_score)>threshold:
      outliers.append(i)


      return outliers

detect_outliers(dataset)



